Add example Node express app with Application Access
gravitational/teleport-plugins pull request #147
Opened 2020-11-26 13:56 UTC by marshall-lee

2020-11-27 15:31 UTC, webvictim commented
@marshall-lee https://github.com/gravitational/teleport/pull/4993 is merged.

2020-12-12 14:04 UTC, benarent approved these changes

2020-12-14 11:40 UTC, benarent requested changes
I tried this again over the weekend. I've extra feedback will send along later this week.

2021-01-20 18:37 UTC, benarent approved these changes
I've made a few content tweaks and made things a little easier when running this app with a Teleport Cloud instance.

2021-01-20 19:08 UTC, merged