New Access workflow for Mattermost plugin
gravitational/teleport-plugins pull request #205
Opened 2021-03-30 16:31 UTC by marshall-lee

Closes #187

2021-03-31 04:22 UTC, klizhentas commented
@fspmarshall @r0mant I know you folks are very busy, but need your review on mattermost plugin. We have to deliver it by April 7th release.

2021-03-31 04:45 UTC, fspmarshall approved these changes
I've never used mattermost so I can't really comment on the workflow itself, but code looks good to me :)

2021-03-31 17:08 UTC, r0mant approved these changes

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +		SetHeader("Authorization", "BEARER "+conf.Token)
Nit: Don't think the case matters but I've never seen it capitalized, `Bearer`.

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +func NewBot(conf MattermostConfig, clusterName, webProxyAddr string) (Bot, error) {
Nit: Add godoc.

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +			cache.Add(cacheKey, etagCacheEntry{etag: etag, value: resp.Result()})
Is `cache` goroutine-safe?

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +func (b Bot) HealthCheck(ctx context.Context) error {
Godoc.

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +func (b Bot) GetMe(ctx context.Context) (User, error) {
Godoc.

2021-03-31 17:08 UTC, r0mant commented on access/mattermost/bot.go
> +		return errors[0]
I'd `return trace.NewAggregate(errors...)` instead.

2021-04-02 17:03 UTC, marshall-lee commented on access/mattermost/bot.go
> +			cache.Add(cacheKey, etagCacheEntry{etag: etag, value: resp.Result()})
Yes it uses a mutex internally

2021-04-03 04:06 UTC, klizhentas requested changes
I've tested the plugin and it works! Can you please fix a couple of issues before we move forward:

* [ ] Formatting error in error message:

```
WARN   Failed to notify a suggested reviewer: %q does not look like a valid emailalice request_id:a9770b7a-d6ab-4c43-9e58-c17a3a0f017c request_op:put mattermost/app.go:269
```

* [x] The message from bot should contain the URL of the request and link should be https://teleport:port/web/requests/request-id

2021-04-08 22:23 UTC, merged