Make part of Token sensitive
gravitational/teleport-plugins pull request #318
Opened 2021-09-13 09:26 UTC by ReeceCrossland

Teleport provision token resource has an ID that is the token. The issue is that this should be a sensitive value, we require this to be obscured within tf plans/apply runs.

To tackle this our solution is to split this and have a prefix as the ID instead, so the full token is not exposed.

Since there is no other ID exposed by the Teleport API, our options are limited.

2021-09-27 13:13 UTC, gzigzigzeo requested changes

2021-09-27 13:13 UTC, gzigzigzeo commented on terraform/provider/resource_teleport_provision_token.go
> +	metadata, ok := d.GetOk("metadata")
What would you say if we rephrased this fragment a bit?

```
var m []interface{}

metadata, ok := d.GetOk("metadata")
if !ok {
	m = []interface{}{map[string]interface{}{"name": token}}
} else {
	m, ok := metadata.([]interface{})
	if !ok {
		return diagFromErr(trace.BadParameter("Can not convert %T to []interface{}", a))
	}
	md, ok := m[0].(map[string]interface{})
	if !ok {
		return diagFromErr(trace.BadParameter("Can not convert %T to map[string]interface{}", a))
	}

	md["name"] = token
}

d.Set("metadata", m)
```

2021-09-27 13:13 UTC, gzigzigzeo commented on terraform/provider/resource_teleport_provision_token.go
> +			" or import it to the existing state (terraform import teleport_provision_token." + index.(string) + " " + token + ")"
What happens if `index.(string)` conversion fails?

2021-09-27 13:13 UTC, gzigzigzeo commented on terraform/provider/resource_teleport_provision_token.go
> +	d.SetId(index.(string))
Could convert index to string somewhere at the beginning, handle conversion error and use the result in all cases like this?

2021-09-27 13:13 UTC, gzigzigzeo commented on terraform/provider/resource_teleport_provision_token.go
> +		return diagFromErr(fmt.Errorf("API Error: %v", err))
Could you please explain why it's worth omitting `describeErr` here?

2021-11-10 19:02 UTC, Joerger commented
This has been fixed in #341, thank you for your contribution.

2021-11-10 19:02 UTC, closed without merging