Mark some OIDC fields as sensitive
gravitational/teleport-plugins pull request #415
Opened 2022-01-31 13:21 UTC by dmsergeevN26

Mark both `client_secret` and `google_service_account` as sensitive to avoid leaking

2022-01-31 13:38 UTC, dmsergeevN26 commented
Actually, it might be an autogenerated file. Let me take  a deeper look. First time working with terraform sdk

2022-01-31 14:29 UTC, dmsergeevN26 commented
What was done:
1. Modified the OIDCConnectorV2 path as it changed at some point
2. Ran `make gen-schema`

2022-02-01 14:16 UTC, gzigzigzeo commented
Hey! Thank you! LGTM.

2022-02-01 14:19 UTC, gzigzigzeo requested changes

2022-02-01 14:19 UTC, gzigzigzeo commented on terraform/tfschema/types_terraform.go
> +					Name:       "allow",
Due to the inconsistency in `types.proto` this should be capitalized back manually.

2022-02-01 21:29 UTC, Joerger commented
Thanks for you contribution @dmsergeevN26, I've opened an internal PR (with the changes requested) to get this change reviewed, tested through CI, and merged.

2022-02-02 10:04 UTC, dmsergeevN26 commented
@Joerger Thanks. I will close this one, then.

2022-02-02 10:04 UTC, closed without merging