Expose ClusterMaintenenceConfig options to terraform
gravitational/teleport-plugins pull request #886
Opened 2023-08-09 13:39 UTC by lxea

Implements: https://github.com/gravitational/teleport/issues/26066

2023-08-10 00:09 UTC, Joerger approved these changes

2023-08-10 00:36 UTC, r0mant reviewed
Generally looks good to me but would be good to get @marcoandredinis's review as well.

2023-08-10 00:36 UTC, r0mant commented on terraform/reference.mdx
Shouldn't the reference documentation have been updated to include the new resource as well? @marcoandredinis

2023-08-10 07:16 UTC, tcsc requested changes
This doesn't build cleanly for me:
```
❯ make build
rm -rf example/terraform.tfstate
rm -rf example/terraform.tfstate.backup
rm -rf example/.terraform
rm -rf example/.terraform.lock.hcl
rm -rf ~/.terraform.d/plugins/terraform.releases.teleport.dev/gravitational/teleport/13.3.1/darwin_arm64/*
rm -rf build/*
rm -rf terraform-provider-teleport-v13.3.1-darwin-arm64-bin.tar.gz
go clean
GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o build/terraform-provider-teleport  -ldflags '-w -s'
# github.com/gravitational/teleport-plugins/terraform/tfschema
tfschema/types_terraform.go:16444:24: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:16455:27: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:18089:24: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:18100:27: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21881:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21886:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21889:26: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21891:31: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21892:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21894:42: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
tfschema/types_terraform.go:21894:42: too many errors
make: *** [build] Error 1
```

2023-08-10 08:43 UTC, marcoandredinis commented on terraform/reference.mdx
New resources must be added to `terraform/gen/main.go`
```go
// Create Docs Markdown
var (
	mapResourceSchema = map[string]func(context.Context) (tfsdk.Schema, diag.Diagnostics){
		"cluster_maintenance_config": tfschema.GenSchemaClusterMaintenanceConfigV1,
		// ...
```

2023-08-10 09:44 UTC, lxea commented
> 



> This doesn't build cleanly for me:
> 
> ```
> ❯ make build
> rm -rf example/terraform.tfstate
> rm -rf example/terraform.tfstate.backup
> rm -rf example/.terraform
> rm -rf example/.terraform.lock.hcl
> rm -rf ~/.terraform.d/plugins/terraform.releases.teleport.dev/gravitational/teleport/13.3.1/darwin_arm64/*
> rm -rf build/*
> rm -rf terraform-provider-teleport-v13.3.1-darwin-arm64-bin.tar.gz
> go clean
> GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o build/terraform-provider-teleport  -ldflags '-w -s'
> # github.com/gravitational/teleport-plugins/terraform/tfschema
> tfschema/types_terraform.go:16444:24: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:16455:27: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:18089:24: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:18100:27: obj.Verbs undefined (type *"github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21881:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21886:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21889:26: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21891:31: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21892:106: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21894:42: obj.Verbs undefined (type "github.com/gravitational/teleport/api/types".KubernetesResource has no field or method Verbs)
> tfschema/types_terraform.go:21894:42: too many errors
> make: *** [build] Error 1
> ```

I encountered this issue at some point also, I can't remember how I resolved it, but I think it might be to do with the teleport commit in the go.mod and makefile where it `go mod download`s teleport, it also wont built until #30214 is merged

2023-08-10 10:58 UTC, marcoandredinis commented
This looks mostly good :+1: 

> it also wont built until https://github.com/gravitational/teleport/pull/30214 is merged

Not only merged, but also backported to v13 (teleport-plugins follows only the latest major teleport version)

2023-08-10 23:16 UTC, tcsc approved these changes
Looks good to me once gravitational/teleport#30214 and the subsequent v13 backport are merged.

2023-09-08 13:06 UTC, marcoandredinis commented
Let me know if I should do another pass.
It looks like the CI is failing.

2023-09-14 14:03 UTC, merged